name: Deploy Lawcription Main Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh

        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

        chmod 600 ~/.ssh/id_rsa

        ssh-keyscan -p 65002 145.79.209.205 >> ~/.ssh/known_hosts

    - name: Deploy Main Website
      run: |
        rsync -avz \
        --exclude '.git' \
        --exclude '.github' \
        --exclude '.env' \
        --exclude 'node_modules' \
        --exclude 'storage/logs' \
        --exclude 'medico-legal-admin' \
        -e "ssh -i ~/.ssh/id_rsa -p 65002" \
        ./ \
        u230221157@145.79.209.205:~/public_html/

    - name: Optimize Laravel
      run: |
        ssh -i ~/.ssh/id_rsa -p 65002 \
        u230221157@145.79.209.205 << 'EOF'

        cd ~/public_html

        composer install --no-dev --optimize-autoloader

        php artisan migrate --force

        php artisan optimize:clear

        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

        chmod -R 775 storage
        chmod -R 775 bootstrap/cache

        EOF